pipeline {
  agent  any
  stages {
    stage('clone code') {
      steps {
          git(url: 'http://192.168.219.149:22222/gitlab-instance-0cafae89/k8s-cicd-demo.git', credentialsId: 'gitlab-user-pass', branch: '$BRANCH_NAME', changelog: true, poll: false)
      }
    }
	
    

    stage('unit test') {
      steps {
          sh 'mvn clean test'
      }
    }
 
    stage('sonarqube analysis') {
      agent none
      steps {
        withCredentials([string(credentialsId : 'sonarqube-token' ,variable : 'SONAR_TOKEN' ,)]) {
          withSonarQubeEnv('sonarqube') {
              sh '''mvn sonar:sonar -Dsonar.projectKey=$APP_NAME
echo "mvn sonar:sonar -Dsonar.projectKey=$APP_NAME"'''

          }

          timeout(unit: 'MINUTES', activity: true, time: 5) {
            waitForQualityGate 'true'
          }

        }

      }
    }
  

    stage('build & push') {
      steps {
          sh 'mvn clean package -DskipTests'
          sh 'docker build -f Dockerfile -t $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BUILD_NUMBER .'
          withCredentials([usernamePassword(credentialsId : 'harbor-user-pass' ,passwordVariable : 'DOCKER_PASSWORD' ,usernameVariable : 'DOCKER_USERNAME' ,)]) {
            sh '''echo "$DOCKER_PASSWORD" | docker login $REGISTRY -u "$DOCKER_USERNAME" --password-stdin
docker push $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BUILD_NUMBER'''
          }


      }
    }

    stage('push latest') {
      when {
        branch 'main'
      }
      steps {
          sh 'docker tag $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BUILD_NUMBER $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:latest'
          sh 'docker push $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:latest'

      }
    }

    stage('deploy to dev') {
      steps {
          input(id: 'deploy-to-dev', message: 'deploy to dev?')
          configFileProvider([configFile(fileId: '334d10b5-4bb1-46fb-80e2-8f0c132bf3e8', targetLocation: '/tmp/admin.kubeconfig')]) {
            sh 'mkdir -p ~/.kube/'
            sh 'cp /tmp/admin.kubeconfig ~/.kube/config'
			sh 'kubectl create namespace ks-k8s-cicd-demo || echo "Namespace already exists"'  //提前创建cicd-demo-dev.yaml里面定义的namespace
            sh '''sed -i\'\' "s#REGISTRY#$REGISTRY#" deploy/cicd-demo-dev.yaml
sed -i\'\' "s#DOCKERHUB_NAMESPACE#$DOCKERHUB_NAMESPACE#" deploy/cicd-demo-dev.yaml
sed -i\'\' "s#APP_NAME#$APP_NAME#" deploy/cicd-demo-dev.yaml
sed -i\'\' "s#BUILD_NUMBER#$BUILD_NUMBER#" deploy/cicd-demo-dev.yaml
kubectl apply -f deploy/cicd-demo-dev.yaml'''
          }


      }
    }

    stage('push with tag') {
      agent none
      when {
        expression {
          params.TAG_NAME =~ /v.*/
        }

      }
      steps {
        input(message: 'release image with tag?', submitter: '')
        withCredentials([usernamePassword(credentialsId : 'gitlab-user-pass' ,passwordVariable : 'GIT_PASSWORD' ,usernameVariable : 'GIT_USERNAME' ,)]) {
          sh 'git config --global user.email "910254930@qq.com" '
          sh 'git config --global user.name "Zorin" '
          sh 'git tag -a $TAG_NAME -m "$TAG_NAME" '
          sh 'git push http://$GIT_USERNAME:$GIT_PASSWORD@$GIT_REPO_URL/$GIT_ACCOUNT/k8s-cicd-demo.git --tags --ipv4'
        }

          sh 'docker tag $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:SNAPSHOT-$BUILD_NUMBER $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$TAG_NAME'
          sh 'docker push $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$TAG_NAME'

      }
    }

    stage('deploy to production') {
      agent none
      when {
        expression {
          params.TAG_NAME =~ /v.*/
        }

      }
      steps {
        input(message: 'deploy to production?', submitter: '')
          sh '''sed -i\'\' "s#REGISTRY#$REGISTRY#" deploy/cicd-demo.yaml
sed -i\'\' "s#DOCKERHUB_NAMESPACE#$DOCKERHUB_NAMESPACE#" deploy/cicd-demo.yaml
sed -i\'\' "s#APP_NAME#$APP_NAME#" deploy/cicd-demo.yaml
sed -i\'\' "s#TAG_NAME#$TAG_NAME#" deploy/cicd-demo.yaml

kubectl apply -f deploy/cicd-demo.yaml'''

      }
    }

  }
  environment {
    REGISTRY = '192.168.219.129:80'
    DOCKER_CREDENTIAL_ID = 'harbor-user-pass'
    GIT_REPO_URL = 'http://192.168.219.149:22222'
    GIT_CREDENTIAL_ID = 'gitlab-user-pass'
    KUBECONFIG_CREDENTIAL_ID = '334d10b5-4bb1-46fb-80e2-8f0c132bf3e8'
    DOCKERHUB_NAMESPACE = 'library'
    GITHUB_ACCOUNT = 'root'
    APP_NAME = 'k8s-cicd-demo'
  }
  parameters {
    string(name: 'BRANCH_NAME', defaultValue: 'main', description: '请选择要发布的分支')
    string(name: 'TAG_NAME', defaultValue: 'snapshot', description: '标签名称，必须以 v 开头，例如：v1、v1.0.0')
  }
}
